# docker compose 文件
version: '3.1'
services:
  mysql:
    restart: always
    image: daocloud.io/library/mysql:latest
    container_name: 'mysql'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - "/usr/local/myapp/docker_mysql_tomcat/mysql_data:/var/lib/mysql"
  tomcat:
    restart: always
    image: daocloud.io/library/tomcat:8.5.15-jre8
    container_name: 'tomcat'
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "/usr/local/myapp/docker_mysql_tomcat/tomcat_webapps:/usr/local/tomcat/webapps"
      - "/usr/local/myapp/docker_mysql_tomcat/tomcat_logs:/usr/local/tomcat/logs"